# See https://pre-commit.com for more information
# See https://pre-commit.cgiom/hooks.html for more hooks
exclude: "settings.py"
fail_fast: true
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        -   id: check-case-conflict
        -   id: check-yaml
        -   id: trailing-whitespace
        -   id: mixed-line-ending
            exclude: README.md
        -   id: check-toml
        -   id: check-merge-conflict
        -   id: mixed-line-ending
  -   repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
        -   id: black
            language_version: python3.13
  -   repo: https://github.com/pycqa/flake8
      rev: 5.0.4
      hooks:
        -   id: flake8
            name: flake8
            additional_dependencies: [flake8-typing-imports==1.10.0]
            types: [python]
            args:
              -   --ignore=E203,E266,E402,E501,W503,F403,F401
              -   --max-line-length=127
              -   --max-complexity=18
              -   --select=B,C,E,F,W,T4,B9,E9,F63,F7,F82
              -   --exclude=venv,logs

default_language_version:
  python: python3.13
